sudo: false
language: node_js
os:
  - linux
  - osx
osx_image: xcode8.2
node_js:
  - '6'
  - '4'
addons:
  apt:
    packages:
      - libpng-dev
      - libgflags-dev
before_install: if [[ $TRAVIS_OS_NAME == osx ]]; then brew update && brew install gflags; fi;
