sudo: false
language: node_js
node_js:
  - '6'
  - '4'
os:
  - linux
  - osx
osx_image: xcode8.2
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - libpng-dev
before_install:
  - if [[ $TRAVIS_OS_NAME == 'linux' ]]; then export CC=gcc-5 CXX=g++-5; fi
  - if [[ $TRAVIS_OS_NAME == 'osx' ]]; then brew update && brew install gflags; fi
